LPS/urls.py
from django.conf.urls import url
from django.contrib import admin
from registration import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
#from Coordinator.views import people


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/',include('registration.urls')),
    url(r'^scientist/',include('scientist.urls')),
    url(r'^teacher/',include('teacher.urls')),
    url(r'^Coordinator/',include('Coordinator.urls')),
    #url(r'^people/',people),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.conf.urls import url
from registration import views

app_name='registration'

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^formpage/',views.form_name_view,name="form_name"),
    url(r'^user_login',views.user_login,name="user_login"),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^register',views.register,name='register'),
]

scientist/urls.py
from django.conf.urls import url
from scientist import views

app_name='scientist'

urlpatterns = [
    # url(r'^$',views.index,name="index"),
    # url(r'^mailingaddress',views.mailingaddress,name='mailingaddress'),
    # url(r'^mailingaddress',views.UserMailingAddressUpdateView.as_view(),name='updateaddress'),
    url(r'^mailingaddress',views.ScientistMailingAddressListView.as_view(),name='list'),
    url(r'^create/$',views.ScientistMailingAddressCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.ScientistMailingAddressUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.ScientistMailingAddressDeleteView.as_view(),name='delete'),
    url(r'^addLetter',views.LettersCreateView.as_view(),name='add_letter'),
    url(r'^letters',views.LettersListView.as_view(),name='letter_list'),
    url(r'^updateletter/(?P<pk>\d+)/$',views.LettersUpdateView.as_view(),name="update_letter"),
    url(r'^students',views.StudentsListView.as_view(),name='students_list'),
    url(r'^requestmatch',views.ScientistRequestMatchCreateView.as_view(),name='RequestMatch'),
    url(r'^requests',views.ScientistMatchRequestListView.as_view(),name='Requests'),
    # url(r'^studentinfo',views.StudentInfo.as_view(),name='studentinfo'),

    # url(r'^scientist/',views.index,name="index"),
]

scientist/models.py
from django.db import models
from django.contrib.auth.models import User
from django_localflavor_us.models import USStateField
from registration.models import UserProfileInfo
from Letters.models import Letter
from Students.models import Student

# Create your models here.
class ScientistMailingAddress(models.Model):
    user = models.OneToOneField(User)
    #user = models.OneToOneField(User)
    address_1 = models.CharField( max_length=128)
    address_2 = models.CharField(max_length=128, blank=True)
    city = models.CharField( max_length=64)
    state = USStateField()
    zip_code = models.CharField( max_length=5)

    def get_absolute_url(self):
        return reverse("scientist:updateaddress",kwargs={'pk':self.pk})
    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

class Scientists(models.Model):
    user=models.OneToOneField(User)


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'letters/user_{0}/{1}'.format(instance.user, filename)

class MatchRequest(models.Model):
    scientist = models.ForeignKey(UserProfileInfo,related_name='Requesting_scientist',blank=True,null=True,
        limit_choices_to={'is_scientist':True})
    creationDate = models.DateField(auto_now_add=True)
    fulfilledDate = models.DateField(auto_now_add=False,null=True)
    student = models.ForeignKey(Student,related_name='Matched_student',blank=True,null=True)
    isPending = models.BooleanField(default=True)
    startingDate = models.DateField(auto_now_add=False,null=True)
    def __str__(self):
        return self.scientist.user.username



# class ScientistLetters(models.Model):
#     user = models.ForeignKey(User)
#     letter = models.ForeignKey(Letter)
#     # letterfile = models.FileField(upload_to=user_directory_path,blank=True)
#     # date_of_upload = models.DateField(auto_now_add=True)
#     # description = models.CharField(max_length=100,default=' ')
#     def __str__(self):
#         # Built-in attribute of django.contrib.auth.models.User !
#         return self.letter.description

scientist/forms.py
from django import forms
from django.core import validators
from registration.models import UserProfileInfo
from django.contrib.auth.models import User
from scientist.models import ScientistMailingAddress, MatchRequest
from Letters.models import Letter
#def check_for_z(value):
#    if value[0].upper() != 'Z':
#        raise forms.ValidationError("Name needs to start with Z!!")

class DateInput(forms.DateInput):
    input_type = 'date'

class ScientistMatchRequestForm(forms.ModelForm):

    class Meta():
        model = MatchRequest
        fields = ('startingDate',)
        labels = {
        'startingDate': "Start Date",

        }
        widgets = {'startingDate':DateInput(),}



class ScientistMailingAddressForm(forms.ModelForm):

    class Meta():
        model = ScientistMailingAddress
        fields = ('address_1','address_2','city','state','zip_code')
        labels = {
        'zip_code': "Zip Code",
        'address_1':"Address",
        'address_2':"Address cont"
        }

class ScientistLettersForm(forms.ModelForm):
    class Meta():
        model = Letter
        fields = ('letterfile','description','student','sent_date',)
        labels = {
        'letterfile':"Letter",
        'description':"Description",
        'student':"For Student",
        'sent_date':"Date Sent"
        }
        widgets = {'sent_date':DateInput(),}

scientist/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (View,TemplateView,ListView,DetailView,
    CreateView,UpdateView,DeleteView)
from django.http import HttpResponseRedirect
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django_tables2.export.views import ExportMixin
from django_filters import rest_framework as filters

from scientist.forms import ScientistMailingAddressForm,ScientistLettersForm,ScientistMatchRequestForm
from scientist.models import ScientistMailingAddress,Scientists, MatchRequest
from registration.models import UserProfileInfo
from Students.models import Student
from Letters.models import Letter
from scientist.tables import MatchRequestTable

# Create your views here.
class ScientistRequestMatchCreateView(CreateView):
    model = MatchRequest
    #fields=('startingDate',)
    success_url = reverse_lazy('scientist:Requests')
    form_class = ScientistMatchRequestForm
    def form_valid(self,form):
        obj = form.save(commit=False)
        self.object = obj
        obj.scientist = UserProfileInfo.objects.get(user=self.request.user)
        obj.isPending = True
        obj.save()
        return super(ScientistRequestMatchCreateView,self).form_valid(form)

class ScientistMatchRequestListView(ExportMixin,SingleTableMixin, FilterView):
    table_class = MatchRequestTable
    model = MatchRequest
    template_name = 'scientist/matchrequest_list.html'
    export_name = 'requests'
    filter_fields = {'scientist':['exact'],'isPending':['exact'], 'startingDate':['year','year__gt','year__lt']}
    #filter_fields = ('scientist','student','creationDate')
    # def get_queryset(self):
    #     return MatchRequest.objects.filter(scientist=self.request.user.id)
    def get_queryset(self):
        print (self.request.user.id)
        return MatchRequest.objects.filter(scientist=UserProfileInfo.objects.get(user=self.request.user))

class ScientistMailingAddressCreateView(CreateView):
    model = ScientistMailingAddress
    fields=('address_1','address_2','city','state','zip_code')
    success_url = reverse_lazy('scientist:list')
    # print(self.kwargs.get('pk'))
    def form_valid(self, form):
        obj = form.save(commit=False)
        self.object = obj
        print(self.request.user)
        obj.user_id = self.request.user.pk
        obj.save()
        # return HttpResponseRedirect(self.get_success_url())
        # form.instance.user_id = self.kwargs.get('pk')
        return super(ScientistMailingAddressCreateView, self).form_valid(form)

class ScientistMailingAddressUpdateView(UpdateView):
    model = ScientistMailingAddress
    fields=('address_1','address_2','city','state','zip_code')
    success_url = reverse_lazy('scientist:list')

class ScientistMailingAddressListView(ListView):
    model = ScientistMailingAddress
    context_object_name = 'scimailingaddresses'
    # context_object_name = 'schools' #default is school_list
    def get_queryset(self):
        return ScientistMailingAddress.objects.filter(user_id=self.request.user.pk)

class ScientistMailingAddressDeleteView(DeleteView):
    model = ScientistMailingAddress
    success_url = reverse_lazy('scientist:list')

class ScientistMailingAddressListView(ListView):
    model = ScientistMailingAddress
    context_object_name = 'scimailingaddresses'
    # context_object_name = 'schools' #default is school_list
    def get_queryset(self):
        return ScientistMailingAddress.objects.filter(user_id=self.request.user.pk)


class LettersCreateView(CreateView):
    model = Letter
    context_object_name = 'letters'
    # fields=('letterfile',)
    success_url = reverse_lazy('scientist:letter_list')
    form_class = ScientistLettersForm
    # print(self.kwargs.get('pk'))
    def form_valid(self, form):
        obj = form.save(commit=False)
        self.object = obj
        # print(self.request.user)
        obj.scientist_id = self.request.user.pk
        obj.from_scientist = True
        obj.save()
        return super(LettersCreateView, self).form_valid(form)

class LettersListView(ListView):
    model = Letter
    context_object_name = 'letters_list'
    queryset = Student.objects.order_by('-date_of_upload')
    # context_object_name = 'schools' #default is school_list
    def get_queryset(self):
        # print(self.request.user.pk)
        # print(self.request.user)
        return Letter.objects.filter(scientist_id=self.request.user.pk)

class LettersUpdateView(UpdateView):
    model = Letter
    context_object_name = 'letters'
    form_class = ScientistLettersForm
    template_name = "scientist/scientistletters_form.html"
    # fields=('sent_date','letterfile','description','student')
    success_url = reverse_lazy('scientist:letter_list')
    def form_valid(self, form):
        obj = form.save(commit=False)
        self.object = obj
        obj.from_scientist = True
        obj.save()
        return super(LettersCreateView, self).form_valid(form)

class StudentsListView(ListView):
    model = Student
    context_object_name = 'students'
    template_name = 'scientist/student_list.html'
    def get_queryset(self):
        # print(self.request.user.pk)
        # print(self.request.user)
        return Student.objects.filter(scientist_id=self.request.user.pk)

scientist/templates/scientist/matchrequest_form.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>
Request Match
</h1>
 <form method="post"  enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.as_p}}
   <input type="submit" class="btn btn-primary" value="Save">
   <a class="btn btn-success" href="{% url 'scientist:list' %}">Cancel</a><br><br>
 </form>
{%endblock%}

scientist/templates/scientist/matchrequest_list.html
{% extends "scientist/scientist_base.html"%}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}

{%block body_block %}
<h1>Requests</h1>
<br>

<a href="{% querystring '_export'='csv' %}">Export to CSV</a>

<hr><h4>Filter</h4>
{% if filter %}
    <form action="" method="get" class="form form-inline">
      {{filter.form.as_table}}
        <!-- {% bootstrap_form filter.form layout='inline' %} -->
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
<hr>
<br>
{% render_table table %}

{%endblock%}

scientist/templates/scientist/scientist_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Letters to a PreScientist</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      {% if user.is_authenticated %}
        <div class="d-block p-3 text-center text-white bg-primary">

          <p>Welcome {{ user.username }}!</p>
        </div>
      {% endif %}
      <div class="container">
        <ul class="nav navbar-nav">

          <!-- {# Django Home Link / Admin Link / Register Link#} -->
          <li><a class="navbar-brand" href="{% url 'index' %}">LPS</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

          <!-- {# Some logic on what to display for last item#} -->
          {% if user.is_authenticated %}
            <li><a href="{% url 'registration:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'registration:user_login' %}">Login</a></li>
            <li><a class="navbar-link" href="{% url 'registration:register'%}">Registration</a></li>
          {% endif %}
            <li><a class="navbar-link" href="{% url 'registration:index'%}">Main Menu</a></li>

        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

scientist/templates/scientist/scientistletters_form.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>
Upload Letter
</h1>
 <form method="post"  enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.as_p}}
   <input type="submit" class="btn btn-primary" value="Save">
   <a class="btn btn-success" href="{% url 'scientist:letter_list' %}">Cancel</a><br><br>
 </form>
{%endblock%}

scientist/templates/scientist/scientistmailingaddress_confirm_delete.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}

<h1>Delete {{scimailingaddress.address_1}} {{scimailingaddress.address_2}}
{{scimailingaddress.city}}
{{scimailingaddress.state}}
{{scimailingaddress.zip_code}}?</h1>
<form  method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'scientist:list' %}">Cancel</a>
</form>

{%endblock%}

scientist/templates/scientist/scientistmailingaddress_form.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>
{% if not form.instance.pk %}
Create Mailing Address
{% else %}
  Update Mailing Address

{%endif%}
</h1>
 <form method="post">
   {% csrf_token %}
   {{ form.as_p}}
   <input type="submit" class="btn btn-primary" value="Save" >
 </form>
{%endblock%}

scientist/templates/scientist/scientistmailingaddress_list.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>Address Info</h1>
  <table class="table table-hover">
    {%for scimailingaddress in scimailingaddresses %}

      <tr><td>{{scimailingaddress.address_1}}</td></tr>
      <tr><td>{{scimailingaddress.address_2}}</td></tr>
      <tr><td>{{scimailingaddress.city}}</td></tr>
      <tr><td>{{scimailingaddress.state}}</td></tr>
      <tr><td>{{scimailingaddress.zip_code}}</td></tr>


  </table>

  <a class="btn btn-danger" href="{% url 'scientist:update' pk=scimailingaddress.pk%}">Update Address</a><br><br>
  <a class="btn btn-danger" href="{% url 'scientist:delete' pk=scimailingaddress.pk%}">Delete Address</a><br>
  {%endfor%}
  {% if not scimailingaddresses%}
    <a class="btn btn-danger" href="{% url 'scientist:create'%}">Create Address</a>
  {%endif%}
</ul>
{%endblock%}

scientist/templates/scientist/student_list.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>Student Info</h1>
  <table class="table table-hover">
    <tr>

      <th>First Name</th>
      <th>Last Name</th>
      <th>Grade</th>
      <th>Class</th>
      <th>Interest 1</th>
      <th>Interest 2</th>
      <th>Create Date</th>
    </tr>
    {%for student in students %}
      <tr>

        <td>{{student.firstname}}</td>
        <td>{{student.lastname}}</td>
        <td>{{student.grade}}</td>
        <td>{{student.stud_class}}</td>
        <td>{{student.interest_1}}</td>
        <td>{{student.interest_2}}</td>
        <td>{{student.date_of_upload}}</td>
      </tr>
    {%endfor%}
  </table>


</ul>
{%endblock%}

scientist/templates/scientist/studentinfo_form.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>
{% if not form.instance.pk %}
  Request student!
{% else %}
  Request still pending... Checking back soon!

{%endif%}
</h1>
 <form method="post">
   {% csrf_token %}
   {{ form.as_p}}
   <input type="submit" class="btn btn-primary" value="Submit">
 </form>
{%endblock%}