LPS/urls.py
from django.conf.urls import url
from django.contrib import admin
from registration import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
#from Coordinator.views import people


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/',include('registration.urls')),
    url(r'^scientist/',include('scientist.urls')),
    url(r'^teacher/',include('teacher.urls')),
    url(r'^Coordinator/',include('Coordinator.urls')),
    #url(r'^people/',people),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scientist/urls.py
from django.conf.urls import url
from scientist import views

app_name='scientist'

urlpatterns = [
    # url(r'^$',views.index,name="index"),
    # url(r'^mailingaddress',views.mailingaddress,name='mailingaddress'),
    # url(r'^mailingaddress',views.UserMailingAddressUpdateView.as_view(),name='updateaddress'),
    url(r'^mailingaddress',views.ScientistMailingAddressListView.as_view(),name='list'),
    url(r'^create/$',views.ScientistMailingAddressCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.ScientistMailingAddressUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.ScientistMailingAddressDeleteView.as_view(),name='delete'),
    url(r'^addLetter',views.LettersCreateView.as_view(),name='add_letter'),
    url(r'^letters',views.LettersListView.as_view(),name='letter_list'),
    url(r'^updateletter/(?P<pk>\d+)/$',views.LettersUpdateView.as_view(),name="update_letter"),
    url(r'^students',views.StudentsListView.as_view(),name='students_list'),
    url(r'^requestmatch',views.ScientistRequestMatchCreateView.as_view(),name='RequestMatch'),
    url(r'^requests',views.ScientistMatchRequestListView.as_view(),name='Requests'),
    # url(r'^studentinfo',views.StudentInfo.as_view(),name='studentinfo'),

    # url(r'^scientist/',views.index,name="index"),
]

teacher/urls.py
from django.conf.urls import url
from teacher import views

app_name='teacher'

urlpatterns = [
 url(r'^letters',views.LettersListView.as_view(),name='tletter_list'),
 url(r'^addLetter',views.LettersCreateView.as_view(),name='add_letter'),
 url(r'^updateletter/(?P<pk>\d+)/$',views.LettersUpdateView.as_view(),name="update_letter"),
 url(r'^students',views.StudentsListView.as_view(),name='students_list'),
 url(r'^addStudent',views.StudentsCreateView.as_view(),name='add_student'),
]

Letters/models.py
from django.db import models
from django.contrib.auth.models import User
from registration.models import UserProfileInfo
from Students.models import Student
# Create your models here.
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'letters/user_{0}/{1}'.format(instance.scientist, filename)


class Letter(models.Model):
    letterfile = models.FileField(upload_to='letters/',blank=True)
    date_of_upload = models.DateField(auto_now_add=True)
    description = models.CharField(max_length=100,default=' ')
    scientist = models.ForeignKey(User,related_name='Scientist')
    student = models.ForeignKey(Student)
    sent_date = models.DateField(blank=True,null=True)
    received_date = models.DateField(blank=True,null=True)
    from_student = models.BooleanField(default=False)
    from_scientist = models.BooleanField(default=False)
    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.description

Letters/views.py
from django.shortcuts import render

# Create your views here.

Letters/templates/Letters/letter_form.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>
Letters
</h1>
 <form method="post"  enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.as_p}}
   <input type="submit" class="btn btn-primary" value="Save">
   
 </form>
{%endblock%}

Letters/templates/Letters/letter_list.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>Scientist Letter Info</h1>

    <table class="table table-hover">
      <tr>
        <th>Letter</th>
        <th>Date of Upload</th>
        <th>Student</th>
        <th>Date Sent</th>

      </tr>
    {%for letter in letters_list %}
      <tr>
        <td>
          {% if letter.letterfile.url%}
          <a href="{{letter.letterfile.url}}" download>{{letter.description}}</a>
          {%endif%}
        </td>
        <td>
          {{letter.date_of_upload}}
        </td>
        <td>{{letter.student}}</td>
        <td>{{letter.sent_date}}</td>
        <td><a class = "btn btn-danger" href="{% url 'scientist:update_letter' pk=letter.pk %}">Edit</a></td>
      </tr>
  {%endfor%}
  </table>
  <a class="btn btn-danger" href="{% url 'scientist:add_letter'%}">Upload Letter</a>

{%endblock%}

Letters/templates/Letters/tletter_list.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>Teacher Letter Info</h1>

    <table class="table table-hover">
      <tr>
        <th>Letter</th>
        <th>Date of Upload</th>
        <th>Scientist</th>
        <th>Student</th>
        <th>Date Sent</th>
        <th>Date Received<th>

      </tr>
    {%for letter in letters_list %}
      <tr>
        <td>
          {% if letter.letterfile.url%}
          <a href="{{letter.letterfile.url}}" download>{{letter.description}}</a>
          {%endif%}
        </td>
        <td>
          {{letter.date_of_upload}}
        </td>
        <td>{{letter.scientist}}</td>
        <td>{{letter.student}}</td>
        <td>{{letter.sent_date}}</td>
        <td>{{letter.received_date}}</td>
        <td><a class = "btn btn-danger" href="{% url 'teacher:update_letter' pk=letter.pk %}">Mark Received</a></td>
      </tr>
  {%endfor%}
  </table>
  <a class="btn btn-danger" href="{% url 'teacher:add_letter'%}">Upload Letter</a>

{%endblock%}