Coordinator/urls.py
from django.conf.urls import url
from Coordinator import views
#from Coordinator.views import people


app_name='Coordinator'

urlpatterns = [
    #url(r'^matched_students',views.MatchedStudentsListView.as_view(),name='students_list'),
    #url(r'^unmatched_students',views.UnmatchedStudentsListView.as_view(),name='unmatched_students_list'),
    #url(r'^unmatched_students',views.StudentListView.as_view(),name='unmatched_students_list'),
    #url(r'^studs',views.people,name='studs'),
    url(r'^students',views.FilteredStudentListView.as_view(),name='students'),
    url(r'^scientists',views.FilteredSciListView.as_view(),name='scientists'),
    url(r'^teachers',views.FilteredTeachListView.as_view(),name='teachers'),
    #url(r'^update_students/(?P<pk>\d+)/$',views.MatchStudentsUpdateView.as_view(),name='update_students'),
    #url(r'^MakeMatch/(?P<pk>\d+)/$',views.MakeMatch.as_view(),name='MakeMatch'),
    url(r'^MakeMatch/(?P<scientist>\d+)/$',views.MakeMatch.as_view(),name='MakeMatch'),
    url(r'^Matches',views.FilteredMatches.as_view(),name='all_matches'),
    url(r'^DeleteMatch/(?P<pk>\d+)/$',views.DeleteMatch.as_view(),name='DeleteMatch'),
    url(r'^BulkUpload',views.BulkUploadView.as_view(),name='BulkUpload'),

    ]

LPS/urls.py
from django.conf.urls import url
from django.contrib import admin
from registration import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
#from Coordinator.views import people


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/',include('registration.urls')),
    url(r'^scientist/',include('scientist.urls')),
    url(r'^teacher/',include('teacher.urls')),
    url(r'^Coordinator/',include('Coordinator.urls')),
    #url(r'^people/',people),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Coordinator/models.py
from django.db import models
import csv
from django.contrib.auth.models import User

from registration.models import UserProfileInfo
from Students.models import Student
from teacher.models import Teachers
# Create your models here.
class Match(models.Model):
    scientist = models.ForeignKey(UserProfileInfo,related_name='Assigned_scientist',blank=True,null=True,limit_choices_to={'is_scientist':True})
    student = models.ForeignKey(Student,related_name='Assigned_student',blank=True,null=True)
    creationDate = models.DateField(auto_now_add=True)
    ActiveDate = models.DateField(auto_now_add=False,null=True)
    DeactiveDate  = models.DateField(auto_now_add=False,null=True)
    is_active = models.BooleanField(default=False)

class CSVFile(models.Model):
    csv_file = models.FileField(upload_to='csvfiles')
    creationDate = models.DateField(auto_now_add=True)

    def save(self,*args,**kwargs):
        super(CSVFile,self).save(*args,**kwargs)
        self.csv_file.open(mode='r')
        f = csv.reader(self.csv_file)
        for row in f:

            row_dict = self.row_to_dict(row)
            if row_dict['Teacher'] == 'Teacher':
                continue
            teacher = self.retrieve_teacher(row_dict['Teacher'])
            if teacher:
                print(row_dict)
                student = self.does_stud_exist(row_dict['Firstname'],row_dict['Lastname'],row_dict['Grade'])
                if student is None:
                    print(row_dict)
                    self.create_student(teacher,row_dict)

        self.csv_file.close()

    def retrieve_teacher(self,teacher):
        try:
            return User.objects.get(username=teacher)

        except User.DoesNotExist:
            return None

    def does_stud_exist(self,firstname,lastname,grade):

        try:
            return Student.objects.get(firstname=firstname,lastname=lastname,grade=grade)
        except Student.DoesNotExist:
            return None
        except Student.MultipleObjectsReturned:
            return Student.objects.filter(firstname=firstname,lastname=lastname,grade=grade)[0]

    def row_to_dict(self,row):
        return {'Teacher':row[0],'Scientist':row[1],'Firstname':row[2],'Lastname':row[3],'Grade':row[4],'Stud Class':row[5],
        'Interest 1':row[6],'Interest 2':row[7]}

    def create_student(self,teacher,row_dict):
        Student.objects.create(
            teacher = teacher,
            firstname = row_dict['Firstname'],
            lastname = row_dict['Lastname'],
            grade = row_dict['Grade'],
            stud_class = row_dict['Stud Class'],
            interest_1 = row_dict['Interest 1'],
            interest_2 = row_dict['Interest 2'],
        )

Students/models.py
from django.db import models
from django.contrib.auth.models import User
from registration.models import UserProfileInfo

# Create your models here.
class Student(models.Model):
    teacher = models.ForeignKey(User,related_name='Teacher')
    scientist = models.ForeignKey(User,related_name='Assigned_scientist',blank=True,null=True)
    firstname = models.CharField(max_length=25)
    lastname = models.CharField(max_length=50)
    grade = models.IntegerField()
    stud_class = models.CharField(max_length=50)
    interest_1 = models.CharField(max_length=128)
    interest_2 = models.CharField(max_length=128)
    date_of_upload = models.DateField(auto_now_add=True)
    def __str__(self):
    # Built-in attribute of django.contrib.auth.models.User !
        return self.firstname +"_"+ self.lastname

Coordinator/forms.py
#from crispy_forms.helper import FormHelper
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from crispy_forms.bootstrap import InlineField, FormActions,StrictButton
from django import forms

from Students.models import Student
from scientist.models import Scientists
from registration.models import UserProfileInfo
from Coordinator.models import Match

class MatchScientist(forms.ModelForm):
    class Meta():
        model = Match
        
        fields = ('scientist','student','is_active')
        labels = { 'scientist':"Scientist",
                    'student':'Student',
                    'is_active':'Active Match?',
        }
class CoordinatorStudentForm(forms.ModelForm):
    class Meta():
        model = Student
        fields = ('scientist',)
        labels = {
        'scientist':"Scientist",
        }


class StudentListFormHelper(FormHelper):
    form_id = 'student-search-form'
    form_class = 'form-inline'
    field_template = 'bootstrap3/layout/inline_field.html'
    field_class = 'col-xs-3'
    label_class = 'col-xs-3'
    form_show_errors = True
    help_text_inline = False
    html5_required = True
    layout = Layout(
                Fieldset(
                    '<i class="fa fa-search"></i> Search Student Records',
                    InlineField('teacher'),
                    InlineField('student_last_name'),
                    InlineField('student_first_name'),
                    InlineField('primary_phone'),
                ),
                FormActions(
                    StrictButton(
                        '<i class="fa fa-search"></i> Search',
                        type='submit',
                        css_class='btn-primary',
                        style='margin-top:10px;')
                )
    )

Coordinator/views.py
from django.views.generic import ListView,UpdateView,CreateView,DeleteView
from django.shortcuts import render
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django_tables2.export.views import ExportMixin
from django_filters import rest_framework as filters
from django.core.urlresolvers import reverse_lazy

from Coordinator.forms import CoordinatorStudentForm,MatchScientist
from Coordinator.tables import StudentTable,SciTable,MatchTable,TeachTable
from registration.models import UserProfileInfo
from Coordinator.filters import StudentListFilter,SciListFilter
from Students.models import Student
from scientist.models import Scientists
from Coordinator.models import Match, CSVFile

# Create your views here.

class BulkUploadView(CreateView):
    model = CSVFile
    context_object_name = 'student_list'
    # fields=('letterfile',)
    success_url = reverse_lazy('Coordinator:students')
    fields = ['csv_file',]
    #form_class = ScientistLettersForm
    # print(self.kwargs.get('pk'))


class DeleteMatch(DeleteView):
    model = Match
    template_name = 'coordinator/del_match.html'


class MakeMatch(CreateView):
    model = Match
    context_object_name = "MakeMatch"
    form_class = MatchScientist
    success_url = reverse_lazy('Coordinator:scientists')
    template_name = 'coordinator/student_form.html'

    def get_initial(self):
        return {'scientist':self.kwargs['scientist']}

class FilteredMatches(ExportMixin,SingleTableMixin, FilterView):
    table_class = MatchTable
    model = Match
    template_name = 'coordinator/match_list.html'
    export_name = 'LPS_Matches'
    filter_fields = {'scientist':['exact'],'student':['exact'], 'creationDate':['year','year__gt','year__lt']}
    #filter_fields = ('scientist','student','creationDate')


class FilteredSciListView(ExportMixin,SingleTableMixin, FilterView):
    table_class = SciTable
    model = UserProfileInfo
    template_name = 'coordinator/sci_list.html'
    #filterset_class = SciListFilter
    export_name= 'Scientists'
    filter_fields = {
    'user':['exact'],'user__email':['contains'],'is_matched':['exact'], 'is_being_matched':['exact'],
    }

    #filter_backends = (filters.DjangoFilterBackend,)

    def get_queryset(self):
    #     # print(self.request.user.pk)
#         print(self.request.user.email)
         return UserProfileInfo.objects.exclude(is_scientist = False)


class FilteredTeachListView(ExportMixin,SingleTableMixin, FilterView):
    table_class = TeachTable
    model = UserProfileInfo
    template_name = 'coordinator/teach_list.html'
    #filterset_class = SciListFilter
    export_name= 'Teachers'
    filter_fields = {
    'user':['exact'],'user__email':['contains'],
    }

    def get_queryset(self):
         return UserProfileInfo.objects.exclude(is_teacher = False)

class FilteredStudentListView(ExportMixin,SingleTableMixin, FilterView):
    table_class = StudentTable
    model = Student
    template_name = 'coordinator/stud_list0.html'
    #filterset_class = StudentListFilter
    fields = ['teacher','scientist','firstname','lastname','grade','stud_class']
    filter_fields = {
    'teacher':['exact'],
    'scientist':['exact'],
    'firstname':['contains'],
    'lastname':['contains'],
    'grade':['exact'],
    'stud_class':['exact'],
    }
    export_name= 'Students'

Students/views.py
from django.shortcuts import render

# Create your views here.

Coordinator/templates/coordinator/csvfile_form.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>
Upload Student List
</h1>
 <form method="post"  enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.as_p}}
   <input type="submit" class="btn btn-primary" value="Save">
   <a class="btn btn-success" href="{% url 'Coordinator:students' %}">Cancel</a><br><br>
 </form>
{%endblock%}

Coordinator/templates/coordinator/del_match.html
{% extends "scientist/scientist_base.html"%}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load bootstrap3 %}

{%block body_block %}
<h1>Deleted Successfully</h1>
<br>
<a href="{% querystring '_export'='csv' %}">Export to CSV</a>

{% if filter %}
    <form action="" method="get" class="form form-inline">
      {{filter.form.as_table}}
        <!-- {% bootstrap_form filter.form layout='inline' %} -->
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
{% render_table table %}

{%endblock%}

Coordinator/templates/coordinator/match_list.html
{% extends "scientist/scientist_base.html"%}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load bootstrap3 %}

{%block body_block %}
<h1>All Matches</h1>
<br>
<a href="{% querystring '_export'='csv' %}">Export to CSV</a>

{% if filter %}
    <form action="" method="get" class="form form-inline">
      {{filter.form.as_table}}
        <!-- {% bootstrap_form filter.form layout='inline' %} -->
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
{% render_table table %}

{%endblock%}

Coordinator/templates/coordinator/sci_list.html
{% extends "scientist/scientist_base.html"%}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}

{%block body_block %}
<h1>Scientists</h1>
<br>

<a href="{% querystring '_export'='csv' %}">Export to CSV</a>

<hr>
{% if filter %}
    <form action="" method="get" class="form form-inline">
      {{filter.form.as_p}}
        <!-- {% bootstrap_form filter.form layout='inline' %} -->
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
<hr>
<br>
{% render_table table %}

{%endblock%}

Coordinator/templates/coordinator/stud_list0.html
{% extends "scientist/scientist_base.html"%}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}

{%block body_block %}
<h1>Students</h1>
<br>
<a href="{% querystring '_export'='csv' %}">Export to CSV</a><br>
<a href="{% url 'Coordinator:BulkUpload' %}">Upload CSV</a><br>
{% if filter %}
  
    <form action="" method="get" class="form form-inline">
      {{filter.form.as_p}}
        <!-- {% bootstrap_form filter.form layout='inline' %} -->
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
{% render_table table %}

{%endblock%}

Coordinator/templates/coordinator/student_form.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}
<h1>
Set Match
</h1>
 <form method="post"  enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.as_p}}
   <input type="submit" class="btn btn-primary" value="Save">
   <a class="btn btn-success" href="{% url 'Coordinator:scientists' %}">Cancel</a><br><br>
 </form>
{%endblock%}

Coordinator/templates/coordinator/student_list.html
{% extends "scientist/scientist_base.html"%}

{%block body_block %}

{%with students|first as stud%}
{% if stud.scientist == None %}
<h2>Unmatched Students</h2>
{% else %}
<h2>Matched Students</h2>
{% endif%}
{%endwith%}
  <table class="table table-hover">
    <tr>
      <th>Scientist</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Grade</th>
      <th>Class</th>
      <th>Interest 1</th>
      <th>Interest 2</th>
      <th>Create Date</th>
      <th>Match/UnMatch</th>
    </tr>
    {%for student in students %}
      <tr>
        <td>{{student.scientist}}</td>
        <td>{{student.firstname}}</td>
        <td>{{student.lastname}}</td>
        <td>{{student.grade}}</td>
        <td>{{student.stud_class}}</td>
        <td>{{student.interest_1}}</td>
        <td>{{student.interest_2}}</td>
        <td>{{student.date_of_upload}}</td>
        <td><a class = "btn btn-danger" href="{% url 'Coordinator:update_students' pk=student.pk %}">Match/UnMatch</a></td>
      </tr>
    {%endfor%}
  </table>


</ul>
{%endblock%}

Coordinator/templates/coordinator/teach_list.html
{% extends "scientist/scientist_base.html"%}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}

{%block body_block %}
<h1>Teachers</h1>
<br>

<a href="{% querystring '_export'='csv' %}">Export to CSV</a>

<hr><h4>Filter</h4>
{% if filter %}
    <form action="" method="get" class="form form-inline">
      {{filter.form.as_table}}
        <!-- {% bootstrap_form filter.form layout='inline' %} -->
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
<hr>
<br>
{% render_table table %}

{%endblock%}